### ISSUE TITLE
REentregar

### ISSUE THREAD

**Issue by egenender** [lmberard/tp3-tda#2]
Podemos notar que si existe un conjunto C con |C| < k soluci´on de HSP, entonces existe soluci´on para Vertex-Cover con el conjunto de nodos igual a C y mismo k.

¿Por qué? ¿Cómo puede explicarse ese fenómeno, por qué se da esa situación?

> Algoritmo backtracking

Esta es la razón principal de la reentrega, y se dan dos factores.

1- A nivel teórico, el algoritmo carece de podas, solamente verificar no pasarse de la longitud máxima establecida. Tener en cuenta además que la forma de iterar hacer que se prueben por ejemplo los jugadores 1,2,3; y luego 2,1,3; y también 2,3,1; etc. En definitiva se vuelven a probar combinaciones que ya fueron probadas. Esto a nivel teórica ya requiere un reformulación del algoritmo de Backtracking.

2- Si bien se modificó el formato de los datos de entrada, todavía es posible leer los archivos originales de prueba ofrecidos, los cuales están en la carpeta data. El problema es que el tiempo que toma el algoritmo de backtracking en resolver estos ejemplos es demasiado elevado. En el mejor de los casos todos los sets de prueba deberían poder ejecutarse sin superar 1 minuto. En casos subóptimos puede darse que el archivo 200.txt tome en torno a los 5 minutos.
En su caso la velocidad se degrada muy rápidamente, tomando bastante tiempo ya el caso de 50, y el de 100 lo detuve tras 1 hora de ejecución ya que no coincide con los tiempos buscados, y predeciblemente el caso de 200 conllevaría aún más tiempo.

Esto conecta con lo descrito a nivel teórico en 1. si se prueban casos de manera repetido y ante la ausencia de podas, el algoritmo o escala adecuadamente.

Les pido reformular el algoritmo de Backtracking para la reentrega.
Recomiendo que usen los casos de prueba que incluso tienen los resultados esperados para constatar el funcionamiento y velocidad.

**Comment by egenender** [comment]
Si bien no quedan representantes del TP cursando de manera regular el correspondiente cuatrimestre, quería hacerme un tiempo para revisar la corrección del algoritmo de Backtracking.

> En casos subóptimos puede darse que el archivo 200.txt tome en torno a los 5 minutos.
> En su caso la velocidad se degrada muy rápidamente, tomando bastante tiempo ya el caso de 50, y el de 100 lo detuve tras 1 hora de ejecución ya que no coincide con los tiempos buscados, y predeciblemente el caso de 200 conllevaría aún más tiempo.

Imagino que habrán experimentado como yo que los tiempos siguen alejados de la hipotética performance que les comenté que estamos buscando.

Saludos

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
tugh, @HoangTuan110, @mapleqin, @navarretega, @zclucky, @may-star-ua, @JustinG1552, @rhythm-sharma, @HsienW, @code-haven, @j4k0m, @sethdford, @antoniocastanheira, @Doppp, @Alexisvt, @thamthee, @devon-mp, @DennisPitallano, @edwardandy, @EvgeniyZh777, @adeolu98, @viannaandreBR, @0xthierry, @Wabbas0, @Robert-H-Leonard, @juanfmange, @trong0dn, @SorenWray, @anastasiarods, @serkan1221, @ronjon22820, @nbompetsis, @124t, @srikar0905, @ErwinRussel, @camiloh95, @netzartist, @saurabhrane1199, @hani-z, @xitong-0629, @dbstratta, @Butters3388214, @Frac7, @FrederikBolding, @Rogebram, @Obamma001, @rafaelsachetto, @josephagwom090, @jamiedevsandbox, @johnnylambadausaspace, @NikitaSmithTheOne, @i0Ek3, @Pomelo1213, @zyhong, @shamzy1, @kendavar, @HenryFanDi, @frankpengau, @fridaymeng, @pawan-meena, @liuderchi, @sotogold, @JohannaVan, @gpetrov, @cow12331, @wisbech, @ronjon22820, @joseandro, @doannc2212, @isaiahxs, @sgc109, @LuPoYi, @nanyang24, @jarrodconnolly, @deroberon, @kitkotcat, @Goodday1212, @quisen, @yifan-gu, @cwww3, @SorenWray, @ee99ee, @jumbojett, @rltbg, @ryooo, @tomgtqq, @exherb, @yaa-seen, @bfriebel, @folowing, @blockchainian, @Sturmol, @kenisad5566, @sarascahya, @transferdeer, @Dan346ibe, @diinesavane, @jacobdmn, @maxoumime
